[package]
name = "kubernetes"
version = "0.1.0"
authors = ["Angus Lees <gus@inodes.org>"]

[dependencies]
url = "1.6"
hyper = "0.11"
hyper-tls = "0.1"
native-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
serde_urlencoded = "0.5"
futures = "0.1.14"
tokio-core = "0.1.12"
failure = "0.1.1"
base64 = "0.9"
log = "0.4"
openssl = "0.10"

[dev-dependencies]
pretty_env_logger = "0.2"
serde_test = "1.0"
